onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /SAD_top/data_in0
add wave -noupdate /SAD_top/data_in1
add wave -noupdate /SAD_top/data_in2
add wave -noupdate /SAD_top/data_in3
add wave -noupdate /SAD_top/data_in4
add wave -noupdate /SAD_top/data_in5
add wave -noupdate /SAD_top/data_in6
add wave -noupdate /SAD_top/data_in7
add wave -noupdate /SAD_top/data_in8
add wave -noupdate /SAD_top/data_in9
add wave -noupdate /SAD_top/data_in10
add wave -noupdate /SAD_top/data_in11
add wave -noupdate /SAD_top/data_in12
add wave -noupdate /SAD_top/data_in13
add wave -noupdate /SAD_top/data_in14
add wave -noupdate /SAD_top/data_in15
add wave -noupdate /SAD_top/data_in16
add wave -noupdate /SAD_top/data_in17
add wave -noupdate /SAD_top/data_in18
add wave -noupdate /SAD_top/data_in19
add wave -noupdate /SAD_top/data_in20
add wave -noupdate /SAD_top/data_in21
add wave -noupdate /SAD_top/data_in22
add wave -noupdate /SAD_top/data_in23
add wave -noupdate /SAD_top/data_in24
add wave -noupdate /SAD_top/data_in25
add wave -noupdate /SAD_top/data_in26
add wave -noupdate /SAD_top/data_in27
add wave -noupdate /SAD_top/data_in28
add wave -noupdate /SAD_top/data_in29
add wave -noupdate /SAD_top/data_in30
add wave -noupdate /SAD_top/data_in31
add wave -noupdate /SAD_top/clk
add wave -noupdate /SAD_top/rst
add wave -noupdate /SAD_top/wr
add wave -noupdate /SAD_top/empty0
add wave -noupdate /SAD_top/empty1
add wave -noupdate /SAD_top/empty2
add wave -noupdate /SAD_top/empty3
add wave -noupdate /SAD_top/empty4
add wave -noupdate /SAD_top/empty5
add wave -noupdate /SAD_top/empty6
add wave -noupdate /SAD_top/empty7
add wave -noupdate /SAD_top/empty8
add wave -noupdate /SAD_top/empty9
add wave -noupdate /SAD_top/empty10
add wave -noupdate /SAD_top/empty11
add wave -noupdate /SAD_top/empty12
add wave -noupdate /SAD_top/empty13
add wave -noupdate /SAD_top/empty14
add wave -noupdate /SAD_top/empty15
add wave -noupdate /SAD_top/empty16
add wave -noupdate /SAD_top/empty17
add wave -noupdate /SAD_top/empty18
add wave -noupdate /SAD_top/empty19
add wave -noupdate /SAD_top/empty20
add wave -noupdate /SAD_top/empty21
add wave -noupdate /SAD_top/empty22
add wave -noupdate /SAD_top/empty23
add wave -noupdate /SAD_top/empty24
add wave -noupdate /SAD_top/empty25
add wave -noupdate /SAD_top/empty26
add wave -noupdate /SAD_top/empty27
add wave -noupdate /SAD_top/empty28
add wave -noupdate /SAD_top/empty29
add wave -noupdate /SAD_top/empty30
add wave -noupdate /SAD_top/empty31
add wave -noupdate /SAD_top/full0
add wave -noupdate /SAD_top/full1
add wave -noupdate /SAD_top/full2
add wave -noupdate /SAD_top/full3
add wave -noupdate /SAD_top/full4
add wave -noupdate /SAD_top/full5
add wave -noupdate /SAD_top/full6
add wave -noupdate /SAD_top/full7
add wave -noupdate /SAD_top/full8
add wave -noupdate /SAD_top/full9
add wave -noupdate /SAD_top/full10
add wave -noupdate /SAD_top/full11
add wave -noupdate /SAD_top/full12
add wave -noupdate /SAD_top/full13
add wave -noupdate /SAD_top/full14
add wave -noupdate /SAD_top/full15
add wave -noupdate /SAD_top/full16
add wave -noupdate /SAD_top/full17
add wave -noupdate /SAD_top/full18
add wave -noupdate /SAD_top/full19
add wave -noupdate /SAD_top/full20
add wave -noupdate /SAD_top/full21
add wave -noupdate /SAD_top/full22
add wave -noupdate /SAD_top/full23
add wave -noupdate /SAD_top/full24
add wave -noupdate /SAD_top/full25
add wave -noupdate /SAD_top/full26
add wave -noupdate /SAD_top/full27
add wave -noupdate /SAD_top/full28
add wave -noupdate /SAD_top/full29
add wave -noupdate /SAD_top/full30
add wave -noupdate /SAD_top/full31
add wave -noupdate /SAD_top/FIFO_count0
add wave -noupdate /SAD_top/FIFO_count1
add wave -noupdate /SAD_top/FIFO_count2
add wave -noupdate /SAD_top/FIFO_count3
add wave -noupdate /SAD_top/FIFO_count4
add wave -noupdate /SAD_top/FIFO_count5
add wave -noupdate /SAD_top/FIFO_count6
add wave -noupdate /SAD_top/FIFO_count7
add wave -noupdate /SAD_top/FIFO_count8
add wave -noupdate /SAD_top/FIFO_count9
add wave -noupdate /SAD_top/FIFO_count10
add wave -noupdate /SAD_top/FIFO_count11
add wave -noupdate /SAD_top/FIFO_count12
add wave -noupdate /SAD_top/FIFO_count13
add wave -noupdate /SAD_top/FIFO_count14
add wave -noupdate /SAD_top/FIFO_count15
add wave -noupdate /SAD_top/FIFO_count16
add wave -noupdate /SAD_top/FIFO_count17
add wave -noupdate /SAD_top/FIFO_count18
add wave -noupdate /SAD_top/FIFO_count19
add wave -noupdate /SAD_top/FIFO_count20
add wave -noupdate /SAD_top/FIFO_count21
add wave -noupdate /SAD_top/FIFO_count22
add wave -noupdate /SAD_top/FIFO_count23
add wave -noupdate /SAD_top/FIFO_count24
add wave -noupdate /SAD_top/FIFO_count25
add wave -noupdate /SAD_top/FIFO_count26
add wave -noupdate /SAD_top/FIFO_count27
add wave -noupdate /SAD_top/FIFO_count28
add wave -noupdate /SAD_top/FIFO_count29
add wave -noupdate /SAD_top/FIFO_count30
add wave -noupdate /SAD_top/FIFO_count31
add wave -noupdate /SAD_top/data_out0
add wave -noupdate /SAD_top/data_out1
add wave -noupdate /SAD_top/data_out2
add wave -noupdate /SAD_top/data_out3
add wave -noupdate /SAD_top/data_out4
add wave -noupdate /SAD_top/data_out5
add wave -noupdate /SAD_top/data_out6
add wave -noupdate /SAD_top/data_out7
add wave -noupdate /SAD_top/data_out8
add wave -noupdate /SAD_top/data_out9
add wave -noupdate /SAD_top/data_out10
add wave -noupdate /SAD_top/data_out11
add wave -noupdate /SAD_top/data_out12
add wave -noupdate /SAD_top/data_out13
add wave -noupdate /SAD_top/data_out14
add wave -noupdate /SAD_top/data_out15
add wave -noupdate /SAD_top/data_out16
add wave -noupdate /SAD_top/data_out17
add wave -noupdate /SAD_top/data_out18
add wave -noupdate /SAD_top/data_out19
add wave -noupdate /SAD_top/data_out20
add wave -noupdate /SAD_top/data_out21
add wave -noupdate /SAD_top/data_out22
add wave -noupdate /SAD_top/data_out23
add wave -noupdate /SAD_top/data_out24
add wave -noupdate /SAD_top/data_out25
add wave -noupdate /SAD_top/data_out26
add wave -noupdate /SAD_top/data_out27
add wave -noupdate /SAD_top/data_out28
add wave -noupdate /SAD_top/data_out29
add wave -noupdate /SAD_top/data_out30
add wave -noupdate /SAD_top/data_out31
add wave -noupdate /SAD_top/sad_reg
add wave -noupdate /SAD_top/i
add wave -noupdate /SAD_top/go
add wave -noupdate /SAD_top/data_load
add wave -noupdate /SAD_top/FULL
add wave -noupdate /SAD_top/rd
add wave -noupdate /SAD_top/cp/A0
add wave -noupdate /SAD_top/cp/B0
add wave -noupdate /SAD_top/cp/A1
add wave -noupdate /SAD_top/cp/B1
add wave -noupdate /SAD_top/cp/A2
add wave -noupdate /SAD_top/cp/B2
add wave -noupdate /SAD_top/cp/A3
add wave -noupdate /SAD_top/cp/B3
add wave -noupdate /SAD_top/cp/A4
add wave -noupdate /SAD_top/cp/B4
add wave -noupdate /SAD_top/cp/A5
add wave -noupdate /SAD_top/cp/B5
add wave -noupdate /SAD_top/cp/A6
add wave -noupdate /SAD_top/cp/B6
add wave -noupdate /SAD_top/cp/A7
add wave -noupdate /SAD_top/cp/B7
add wave -noupdate /SAD_top/cp/A8
add wave -noupdate /SAD_top/cp/B8
add wave -noupdate /SAD_top/cp/A9
add wave -noupdate /SAD_top/cp/B9
add wave -noupdate /SAD_top/cp/A10
add wave -noupdate /SAD_top/cp/B10
add wave -noupdate /SAD_top/cp/A11
add wave -noupdate /SAD_top/cp/B11
add wave -noupdate /SAD_top/cp/A12
add wave -noupdate /SAD_top/cp/B12
add wave -noupdate /SAD_top/cp/A13
add wave -noupdate /SAD_top/cp/B13
add wave -noupdate /SAD_top/cp/A14
add wave -noupdate /SAD_top/cp/B14
add wave -noupdate /SAD_top/cp/A15
add wave -noupdate /SAD_top/cp/B15
add wave -noupdate /SAD_top/cp/rst
add wave -noupdate /SAD_top/cp/clk
add wave -noupdate /SAD_top/cp/go
add wave -noupdate /SAD_top/cp/sad_reg
add wave -noupdate -radix unsigned /SAD_top/cp/i
add wave -noupdate /SAD_top/cp/data_load
add wave -noupdate /SAD_top/cp/diff0
add wave -noupdate /SAD_top/cp/diff1
add wave -noupdate /SAD_top/cp/diff2
add wave -noupdate /SAD_top/cp/diff3
add wave -noupdate /SAD_top/cp/diff4
add wave -noupdate /SAD_top/cp/diff5
add wave -noupdate /SAD_top/cp/diff6
add wave -noupdate /SAD_top/cp/diff7
add wave -noupdate /SAD_top/cp/diff8
add wave -noupdate /SAD_top/cp/diff9
add wave -noupdate /SAD_top/cp/diff10
add wave -noupdate /SAD_top/cp/diff11
add wave -noupdate /SAD_top/cp/diff12
add wave -noupdate /SAD_top/cp/diff13
add wave -noupdate /SAD_top/cp/diff14
add wave -noupdate /SAD_top/cp/diff15
add wave -noupdate -radix unsigned -childformat {{{/SAD_top/cp/abs_diff[31]} -radix unsigned} {{/SAD_top/cp/abs_diff[30]} -radix unsigned} {{/SAD_top/cp/abs_diff[29]} -radix unsigned} {{/SAD_top/cp/abs_diff[28]} -radix unsigned} {{/SAD_top/cp/abs_diff[27]} -radix unsigned} {{/SAD_top/cp/abs_diff[26]} -radix unsigned} {{/SAD_top/cp/abs_diff[25]} -radix unsigned} {{/SAD_top/cp/abs_diff[24]} -radix unsigned} {{/SAD_top/cp/abs_diff[23]} -radix unsigned} {{/SAD_top/cp/abs_diff[22]} -radix unsigned} {{/SAD_top/cp/abs_diff[21]} -radix unsigned} {{/SAD_top/cp/abs_diff[20]} -radix unsigned} {{/SAD_top/cp/abs_diff[19]} -radix unsigned} {{/SAD_top/cp/abs_diff[18]} -radix unsigned} {{/SAD_top/cp/abs_diff[17]} -radix unsigned} {{/SAD_top/cp/abs_diff[16]} -radix unsigned} {{/SAD_top/cp/abs_diff[15]} -radix unsigned} {{/SAD_top/cp/abs_diff[14]} -radix unsigned} {{/SAD_top/cp/abs_diff[13]} -radix unsigned} {{/SAD_top/cp/abs_diff[12]} -radix unsigned} {{/SAD_top/cp/abs_diff[11]} -radix unsigned} {{/SAD_top/cp/abs_diff[10]} -radix unsigned} {{/SAD_top/cp/abs_diff[9]} -radix unsigned} {{/SAD_top/cp/abs_diff[8]} -radix unsigned} {{/SAD_top/cp/abs_diff[7]} -radix unsigned} {{/SAD_top/cp/abs_diff[6]} -radix unsigned} {{/SAD_top/cp/abs_diff[5]} -radix unsigned} {{/SAD_top/cp/abs_diff[4]} -radix unsigned} {{/SAD_top/cp/abs_diff[3]} -radix unsigned} {{/SAD_top/cp/abs_diff[2]} -radix unsigned} {{/SAD_top/cp/abs_diff[1]} -radix unsigned} {{/SAD_top/cp/abs_diff[0]} -radix unsigned}} -subitemconfig {{/SAD_top/cp/abs_diff[31]} {-radix unsigned} {/SAD_top/cp/abs_diff[30]} {-radix unsigned} {/SAD_top/cp/abs_diff[29]} {-radix unsigned} {/SAD_top/cp/abs_diff[28]} {-radix unsigned} {/SAD_top/cp/abs_diff[27]} {-radix unsigned} {/SAD_top/cp/abs_diff[26]} {-radix unsigned} {/SAD_top/cp/abs_diff[25]} {-radix unsigned} {/SAD_top/cp/abs_diff[24]} {-radix unsigned} {/SAD_top/cp/abs_diff[23]} {-radix unsigned} {/SAD_top/cp/abs_diff[22]} {-radix unsigned} {/SAD_top/cp/abs_diff[21]} {-radix unsigned} {/SAD_top/cp/abs_diff[20]} {-radix unsigned} {/SAD_top/cp/abs_diff[19]} {-radix unsigned} {/SAD_top/cp/abs_diff[18]} {-radix unsigned} {/SAD_top/cp/abs_diff[17]} {-radix unsigned} {/SAD_top/cp/abs_diff[16]} {-radix unsigned} {/SAD_top/cp/abs_diff[15]} {-radix unsigned} {/SAD_top/cp/abs_diff[14]} {-radix unsigned} {/SAD_top/cp/abs_diff[13]} {-radix unsigned} {/SAD_top/cp/abs_diff[12]} {-radix unsigned} {/SAD_top/cp/abs_diff[11]} {-radix unsigned} {/SAD_top/cp/abs_diff[10]} {-radix unsigned} {/SAD_top/cp/abs_diff[9]} {-radix unsigned} {/SAD_top/cp/abs_diff[8]} {-radix unsigned} {/SAD_top/cp/abs_diff[7]} {-radix unsigned} {/SAD_top/cp/abs_diff[6]} {-radix unsigned} {/SAD_top/cp/abs_diff[5]} {-radix unsigned} {/SAD_top/cp/abs_diff[4]} {-radix unsigned} {/SAD_top/cp/abs_diff[3]} {-radix unsigned} {/SAD_top/cp/abs_diff[2]} {-radix unsigned} {/SAD_top/cp/abs_diff[1]} {-radix unsigned} {/SAD_top/cp/abs_diff[0]} {-radix unsigned}} /SAD_top/cp/abs_diff
add wave -noupdate /SAD_top/cp/sum_clr
add wave -noupdate /SAD_top/cp/sum_load
add wave -noupdate /SAD_top/cp/i_clr
add wave -noupdate /SAD_top/cp/i_inc
add wave -noupdate /SAD_top/cp/sad_load
add wave -noupdate -radix unsigned /SAD_top/cp/pst
add wave -noupdate -radix unsigned /SAD_top/cp/nxt
add wave -noupdate /SAD_top/cp/sum
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {4641 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 208
configure wave -valuecolwidth 176
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {4569 ps} {5444 ps}
